from src.utils.utils_func import (
    modify_raw_parks_data,
)
import pytest
from src.seed import seed
from src.connection import close_db, create_con
from src.data.index import index as data
from src.data.rides import rides


@pytest.fixture(scope="session")
def db():
    """Runs seed before starting tests.
    Yields a database connection object to be used in tests.
    Closes connection to db after tests have ran"""
    test_db = create_con()
    seed(test_db, **data)
    yield test_db
    close_db(test_db)


def test_modify_raw_rides_data(db):
    result = modify_raw_parks_data(rides, db)
    expected = [
        {
            "ride_name": "Steam Trains",
            "ride_type": "Transport Rides",
            "year_opened": 2005,
            "votes": 104,
            "park_id": 2,
        },
        {
            "ride_name": "Small Monorail Cars",
            "ride_type": "Transport Rides",
            "year_opened": 2016,
            "votes": 749,
            "park_id": 7,
        },
        {
            "ride_name": "Large Monorail Train",
            "ride_type": "Transport Rides",
            "year_opened": 2009,
            "votes": 194,
            "park_id": 5,
        },
        {
            "ride_name": "Chairlift Cars",
            "ride_type": "Transport Rides",
            "year_opened": 2023,
            "votes": 438,
            "park_id": 10,
        },
        {
            "ride_name": "Haunted House",
            "ride_type": "Gentle Rides",
            "year_opened": 2000,
            "votes": 84,
            "park_id": 2,
        },
        {
            "ride_name": "Ferris Wheel",
            "ride_type": "Gentle Rides",
            "year_opened": 1999,
            "votes": 840,
            "park_id": 1,
        },
        {
            "ride_name": "Hedge Maze",
            "ride_type": "Gentle Rides",
            "year_opened": 2009,
            "votes": 295,
            "park_id": 5,
        },
        {
            "ride_name": "Merry-Go-Round",
            "ride_type": "Gentle Rides",
            "year_opened": 1999,
            "votes": 106,
            "park_id": 1,
        },
        {
            "ride_name": "Observation Tower",
            "ride_type": "Gentle Rides",
            "year_opened": 2003,
            "votes": 720,
            "park_id": 3,
        },
        {
            "ride_name": "Sportscars",
            "ride_type": "Gentle Rides",
            "year_opened": 2013,
            "votes": 1058,
            "park_id": 6,
        },
        {
            "ride_name": "Racing Cars",
            "ride_type": "Gentle Rides",
            "year_opened": 2006,
            "votes": 20,
            "park_id": 4,
        },
        {
            "ride_name": "Pickup Trucks",
            "ride_type": "Gentle Rides",
            "year_opened": 2015,
            "votes": 60,
            "park_id": 7,
        },
        {
            "ride_name": "Cheshire Cats",
            "ride_type": "Gentle Rides",
            "year_opened": 2018,
            "votes": 306,
            "park_id": 8,
        },
        {
            "ride_name": "Spiral Slide",
            "ride_type": "Gentle Rides",
            "year_opened": 2021,
            "votes": 481,
            "park_id": 9,
        },
        {
            "ride_name": "Dodgems",
            "ride_type": "Gentle Rides",
            "year_opened": 2023,
            "votes": 82,
            "park_id": 10,
        },
        {
            "ride_name": "Space Rings",
            "ride_type": "Gentle Rides",
            "year_opened": 2010,
            "votes": 1068,
            "park_id": 5,
        },
        {
            "ride_name": "Wooden Roller Coaster",
            "ride_type": "Roller Coasters",
            "year_opened": 1999,
            "votes": 2059,
            "park_id": 1,
        },
        {
            "ride_name": "Reversed Wooden Roller Coaster",
            "ride_type": "Roller Coasters",
            "year_opened": 2001,
            "votes": 1947,
            "park_id": 2,
        },
        {
            "ride_name": "Wooden Wild Mouse",
            "ride_type": "Roller Coasters",
            "year_opened": 2000,
            "votes": 1396,
            "park_id": 1,
        },
        {
            "ride_name": "Wooden Wild Mine Ride",
            "ride_type": "Roller Coasters",
            "year_opened": 2000,
            "votes": 1294,
            "park_id": 2,
        },
        {
            "ride_name": "Ladybird Trains",
            "ride_type": "Roller Coasters",
            "year_opened": 2003,
            "votes": 857,
            "park_id": 3,
        },
        {
            "ride_name": "Log Trains",
            "ride_type": "Roller Coasters",
            "year_opened": 2023,
            "votes": 920,
            "park_id": 10,
        },
        {
            "ride_name": "Rocket Cars",
            "ride_type": "Roller Coasters",
            "year_opened": 2017,
            "votes": 1503,
            "park_id": 4,
        },
        {
            "ride_name": "Spinning Cars",
            "ride_type": "Roller Coasters",
            "year_opened": 2003,
            "votes": 1058,
            "park_id": 3,
        },
        {
            "ride_name": "Mine Train Coaster",
            "ride_type": "Roller Coasters",
            "year_opened": 2015,
            "votes": 1302,
            "park_id": 4,
        },
        {
            "ride_name": "Looping Roller Coaster",
            "ride_type": "Roller Coasters",
            "year_opened": 2015,
            "votes": 1956,
            "park_id": 7,
        },
        {
            "ride_name": "Backwards Roller Coaster Train",
            "ride_type": "Roller Coasters",
            "year_opened": 2024,
            "votes": 2057,
            "park_id": 10,
        },
        {
            "ride_name": "Stand-up Roller Coaster",
            "ride_type": "Roller Coasters",
            "year_opened": 2015,
            "votes": 503,
            "park_id": 5,
        },
        {
            "ride_name": "Corkscrew Roller Coaster",
            "ride_type": "Roller Coasters",
            "year_opened": 2013,
            "votes": 1734,
            "park_id": 6,
        },
        {
            "ride_name": "Suspended Swinging Cars",
            "ride_type": "Roller Coasters",
            "year_opened": 2013,
            "votes": 2056,
            "park_id": 4,
        },
        {
            "ride_name": "Suspended Swinging Airplane Cars",
            "ride_type": "Roller Coasters",
            "year_opened": 2016,
            "votes": 2104,
            "park_id": 8,
        },
        {
            "ride_name": "Mini Suspended Coaster",
            "ride_type": "Roller Coasters",
            "year_opened": 2015,
            "votes": 1845,
            "park_id": 7,
        },
        {
            "ride_name": "Mini Suspended Flying Coaster",
            "ride_type": "Roller Coasters",
            "year_opened": 2020,
            "votes": 1003,
            "park_id": 7,
        },
        {
            "ride_name": "Steeplechase",
            "ride_type": "Roller Coasters",
            "year_opened": 2017,
            "votes": 927,
            "park_id": 5,
        },
        {
            "ride_name": "Motorbike Races",
            "ride_type": "Roller Coasters",
            "year_opened": 2014,
            "votes": 1720,
            "park_id": 6,
        },
        {
            "ride_name": "Bobsleigh Coaster",
            "ride_type": "Roller Coasters",
            "year_opened": 2021,
            "votes": 1940,
            "park_id": 9,
        },
        {
            "ride_name": "Reverse Freefall Coaster",
            "ride_type": "Roller Coasters",
            "year_opened": 2022,
            "votes": 2312,
            "park_id": 7,
        },
        {
            "ride_name": "Vertical Drop Roller Coaster",
            "ride_type": "Roller Coasters",
            "year_opened": 2021,
            "votes": 1840,
            "park_id": 9,
        },
        {
            "ride_name": "Twist",
            "ride_type": "Thrill Rides",
            "year_opened": 2000,
            "votes": 48,
            "park_id": 2,
        },
        {
            "ride_name": "Launched Freefall",
            "ride_type": "Thrill Rides",
            "year_opened": 2004,
            "votes": 375,
            "park_id": 3,
        },
        {
            "ride_name": "Pirate Ship",
            "ride_type": "Thrill Rides",
            "year_opened": 1999,
            "votes": 857,
            "park_id": 1,
        },
        {
            "ride_name": "Go Karts",
            "ride_type": "Thrill Rides",
            "year_opened": 2011,
            "votes": 127,
            "park_id": 5,
        },
        {
            "ride_name": "Swinging Inverter Ship",
            "ride_type": "Thrill Rides",
            "year_opened": 2021,
            "votes": 386,
            "park_id": 9,
        },
        {
            "ride_name": "Motion Simulator",
            "ride_type": "Thrill Rides",
            "year_opened": 2016,
            "votes": 285,
            "park_id": 6,
        },
        {
            "ride_name": "3D Cinema",
            "ride_type": "Thrill Rides",
            "year_opened": 2019,
            "votes": 539,
            "park_id": 8,
        },
        {
            "ride_name": "Top Spin",
            "ride_type": "Thrill Rides",
            "year_opened": 2006,
            "votes": 239,
            "park_id": 4,
        },
        {
            "ride_name": "Dinghy Slide",
            "ride_type": "Water Rides",
            "year_opened": 2003,
            "votes": 583,
            "park_id": 3,
        },
        {
            "ride_name": "Log Flume",
            "ride_type": "Water Rides",
            "year_opened": 2007,
            "votes": 739,
            "park_id": 4,
        },
        {
            "ride_name": "River Rapids",
            "ride_type": "Water Rides",
            "year_opened": 2024,
            "votes": 920,
            "park_id": 10,
        },
        {
            "ride_name": "Rowing Boats",
            "ride_type": "Water Rides",
            "year_opened": 2009,
            "votes": 392,
            "park_id": 5,
        },
        {
            "ride_name": "Swans",
            "ride_type": "Water Rides",
            "year_opened": 2013,
            "votes": 295,
            "park_id": 6,
        },
        {
            "ride_name": "Canoes",
            "ride_type": "Water Rides",
            "year_opened": 2015,
            "votes": 21,
            "park_id": 7,
        },
        {
            "ride_name": "Bumper Boats",
            "ride_type": "Water Rides",
            "year_opened": 2018,
            "votes": 520,
            "park_id": 8,
        },
        {
            "ride_name": "Water Tricycles",
            "ride_type": "Water Rides",
            "year_opened": 2023,
            "votes": 133,
            "park_id": 9,
        },
    ]
    assert result == expected
