from src.utils.utils_func import (
    get_parks_data,
    get_rides_data,
    modify_rides_data,
    get_raw_rides_data,
    modify_raw_parks_data
)
import pytest
from src.seed import seed
from src.connection import close_db, create_con
from src.data.index import index as data
from src.data.rides import rides


@pytest.fixture(scope="session")
def db():
    """Runs seed before starting tests.
    Yields a database connection object to be used in tests.
    Closes connection to db after tests have ran"""
    test_db = create_con()
    seed(test_db, **data)
    yield test_db
    close_db(test_db)


def test_get_parks_data(db):
    result = get_parks_data(db)
    expected = [
        {
            "park_id": 1,
            "park_name": "Forest Frontiers",
            "year_opened": 1999,
            "annual_attendance": 250,
        },
        {
            "park_id": 2,
            "park_name": "Dynamite Dunes",
            "year_opened": 2000,
            "annual_attendance": 650,
        },
        {
            "park_id": 3,
            "park_name": "Leafy Lake",
            "year_opened": 2003,
            "annual_attendance": 500,
        },
        {
            "park_id": 4,
            "park_name": "Diamond Heights",
            "year_opened": 2006,
            "annual_attendance": 700,
        },
        {
            "park_id": 5,
            "park_name": "Evergreen Gardens",
            "year_opened": 2009,
            "annual_attendance": 1000,
        },
        {
            "park_id": 6,
            "park_name": "Bumbly Beach",
            "year_opened": 2013,
            "annual_attendance": 750,
        },
        {
            "park_id": 7,
            "park_name": "Trinity Islands",
            "year_opened": 2015,
            "annual_attendance": 750,
        },
        {
            "park_id": 8,
            "park_name": "Katie's Dreamland",
            "year_opened": 2018,
            "annual_attendance": 800,
        },
        {
            "park_id": 9,
            "park_name": "Pokey Park",
            "year_opened": 2021,
            "annual_attendance": 400,
        },
        {
            "park_id": 10,
            "park_name": "White Water Park",
            "year_opened": 2023,
            "annual_attendance": 900,
        },
    ]
    assert result == expected


def test_get_rides_data(db):
    result = get_rides_data(db)
    expected = [
        {
            "ride_id": 1,
            "ride_name": "Steam Trains",
            "ride_type": "Transport Rides",
            "year_opened": 2005,
            "park_name": "Dynamite Dunes",
            "votes": 104,
        },
        {
            "ride_id": 2,
            "ride_name": "Small Monorail Cars",
            "ride_type": "Transport Rides",
            "year_opened": 2016,
            "park_name": "Trinity Islands",
            "votes": 749,
        },
        {
            "ride_id": 3,
            "ride_name": "Large Monorail Train",
            "ride_type": "Transport Rides",
            "year_opened": 2009,
            "park_name": "Evergreen Gardens",
            "votes": 194,
        },
        {
            "ride_id": 4,
            "ride_name": "Chairlift Cars",
            "ride_type": "Transport Rides",
            "year_opened": 2023,
            "park_name": "White Water Park",
            "votes": 438,
        },
        {
            "ride_id": 5,
            "ride_name": "Haunted House",
            "ride_type": "Gentle Rides",
            "year_opened": 2000,
            "park_name": "Dynamite Dunes",
            "votes": 84,
        },
        {
            "ride_id": 6,
            "ride_name": "Ferris Wheel",
            "ride_type": "Gentle Rides",
            "year_opened": 1999,
            "park_name": "Forest Frontiers",
            "votes": 840,
        },
        {
            "ride_id": 7,
            "ride_name": "Hedge Maze",
            "ride_type": "Gentle Rides",
            "year_opened": 2009,
            "park_name": "Evergreen Gardens",
            "votes": 295,
        },
        {
            "ride_id": 8,
            "ride_name": "Merry-Go-Round",
            "ride_type": "Gentle Rides",
            "year_opened": 1999,
            "park_name": "Forest Frontiers",
            "votes": 106,
        },
        {
            "ride_id": 9,
            "ride_name": "Observation Tower",
            "ride_type": "Gentle Rides",
            "year_opened": 2003,
            "park_name": "Leafy Lake",
            "votes": 720,
        },
        {
            "ride_id": 10,
            "ride_name": "Sportscars",
            "ride_type": "Gentle Rides",
            "year_opened": 2013,
            "park_name": "Bumbly Beach",
            "votes": 1058,
        },
        {
            "ride_id": 11,
            "ride_name": "Racing Cars",
            "ride_type": "Gentle Rides",
            "year_opened": 2006,
            "park_name": "Diamond Heights",
            "votes": 20,
        },
        {
            "ride_id": 12,
            "ride_name": "Pickup Trucks",
            "ride_type": "Gentle Rides",
            "year_opened": 2015,
            "park_name": "Trinity Islands",
            "votes": 60,
        },
        {
            "ride_id": 13,
            "ride_name": "Cheshire Cats",
            "ride_type": "Gentle Rides",
            "year_opened": 2018,
            "park_name": "Katie's Dreamland",
            "votes": 306,
        },
        {
            "ride_id": 14,
            "ride_name": "Spiral Slide",
            "ride_type": "Gentle Rides",
            "year_opened": 2021,
            "park_name": "Pokey Park",
            "votes": 481,
        },
        {
            "ride_id": 15,
            "ride_name": "Dodgems",
            "ride_type": "Gentle Rides",
            "year_opened": 2023,
            "park_name": "White Water Park",
            "votes": 82,
        },
        {
            "ride_id": 16,
            "ride_name": "Space Rings",
            "ride_type": "Gentle Rides",
            "year_opened": 2010,
            "park_name": "Evergreen Gardens",
            "votes": 1068,
        },
        {
            "ride_id": 17,
            "ride_name": "Wooden Roller Coaster",
            "ride_type": "Roller Coasters",
            "year_opened": 1999,
            "park_name": "Forest Frontiers",
            "votes": 2059,
        },
        {
            "ride_id": 18,
            "ride_name": "Reversed Wooden Roller Coaster",
            "ride_type": "Roller Coasters",
            "year_opened": 2001,
            "park_name": "Dynamite Dunes",
            "votes": 1947,
        },
        {
            "ride_id": 19,
            "ride_name": "Wooden Wild Mouse",
            "ride_type": "Roller Coasters",
            "year_opened": 2000,
            "park_name": "Forest Frontiers",
            "votes": 1396,
        },
        {
            "ride_id": 20,
            "ride_name": "Wooden Wild Mine Ride",
            "ride_type": "Roller Coasters",
            "year_opened": 2000,
            "park_name": "Dynamite Dunes",
            "votes": 1294,
        },
        {
            "ride_id": 21,
            "ride_name": "Ladybird Trains",
            "ride_type": "Roller Coasters",
            "year_opened": 2003,
            "park_name": "Leafy Lake",
            "votes": 857,
        },
        {
            "ride_id": 22,
            "ride_name": "Log Trains",
            "ride_type": "Roller Coasters",
            "year_opened": 2023,
            "park_name": "White Water Park",
            "votes": 920,
        },
        {
            "ride_id": 23,
            "ride_name": "Rocket Cars",
            "ride_type": "Roller Coasters",
            "year_opened": 2017,
            "park_name": "Diamond Heights",
            "votes": 1503,
        },
        {
            "ride_id": 24,
            "ride_name": "Spinning Cars",
            "ride_type": "Roller Coasters",
            "year_opened": 2003,
            "park_name": "Leafy Lake",
            "votes": 1058,
        },
        {
            "ride_id": 25,
            "ride_name": "Mine Train Coaster",
            "ride_type": "Roller Coasters",
            "year_opened": 2015,
            "park_name": "Diamond Heights",
            "votes": 1302,
        },
        {
            "ride_id": 26,
            "ride_name": "Looping Roller Coaster",
            "ride_type": "Roller Coasters",
            "year_opened": 2015,
            "park_name": "Trinity Islands",
            "votes": 1956,
        },
        {
            "ride_id": 27,
            "ride_name": "Backwards Roller Coaster Train",
            "ride_type": "Roller Coasters",
            "year_opened": 2024,
            "park_name": "White Water Park",
            "votes": 2057,
        },
        {
            "ride_id": 28,
            "ride_name": "Stand-up Roller Coaster",
            "ride_type": "Roller Coasters",
            "year_opened": 2015,
            "park_name": "Evergreen Garden",
            "votes": 503,
        },
        {
            "ride_id": 29,
            "ride_name": "Corkscrew Roller Coaster",
            "ride_type": "Roller Coasters",
            "year_opened": 2013,
            "park_name": "Bumbly Beach",
            "votes": 1734,
        },
        {
            "ride_id": 30,
            "ride_name": "Suspended Swinging Cars",
            "ride_type": "Roller Coasters",
            "year_opened": 2013,
            "park_name": "Diamond Heights",
            "votes": 2056,
        },
        {
            "ride_id": 31,
            "ride_name": "Suspended Swinging Airplane Cars",
            "ride_type": "Roller Coasters",
            "year_opened": 2016,
            "park_name": "Katie's Dreamland",
            "votes": 2104,
        },
        {
            "ride_id": 32,
            "ride_name": "Mini Suspended Coaster",
            "ride_type": "Roller Coasters",
            "year_opened": 2015,
            "park_name": "Trinity Islands",
            "votes": 1845,
        },
        {
            "ride_id": 33,
            "ride_name": "Mini Suspended Flying Coaster",
            "ride_type": "Roller Coasters",
            "year_opened": 2020,
            "park_name": "Trinity Islands",
            "votes": 1003,
        },
        {
            "ride_id": 34,
            "ride_name": "Steeplechase",
            "ride_type": "Roller Coasters",
            "year_opened": 2017,
            "park_name": "Evergreen Garden",
            "votes": 927,
        },
        {
            "ride_id": 35,
            "ride_name": "Motorbike Races",
            "ride_type": "Roller Coasters",
            "year_opened": 2014,
            "park_name": "Bumbly Beach",
            "votes": 1720,
        },
        {
            "ride_id": 36,
            "ride_name": "Bobsleigh Coaster",
            "ride_type": "Roller Coasters",
            "year_opened": 2021,
            "park_name": "Pokey Park",
            "votes": 1940,
        },
        {
            "ride_id": 37,
            "ride_name": "Reverse Freefall Coaster",
            "ride_type": "Roller Coasters",
            "year_opened": 2022,
            "park_name": "Trinity Islands",
            "votes": 2312,
        },
        {
            "ride_id": 38,
            "ride_name": "Vertical Drop Roller Coaster",
            "ride_type": "Roller Coasters",
            "year_opened": 2021,
            "park_name": "Pokey Park",
            "votes": 1840,
        },
        {
            "ride_id": 39,
            "ride_name": "Twist",
            "ride_type": "Thrill Rides",
            "year_opened": 2000,
            "park_name": "Dynamite Dunes",
            "votes": 48,
        },
        {
            "ride_id": 40,
            "ride_name": "Launched Freefall",
            "ride_type": "Thrill Rides",
            "year_opened": 2004,
            "park_name": "Leafy Lake",
            "votes": 375,
        },
        {
            "ride_id": 41,
            "ride_name": "Pirate Ship",
            "ride_type": "Thrill Rides",
            "year_opened": 1999,
            "park_name": "Forest Frontiers",
            "votes": 857,
        },
        {
            "ride_id": 42,
            "ride_name": "Go Karts",
            "ride_type": "Thrill Rides",
            "year_opened": 2011,
            "park_name": "Evergreen Gardens",
            "votes": 127,
        },
        {
            "ride_id": 43,
            "ride_name": "Swinging Inverter Ship",
            "ride_type": "Thrill Rides",
            "year_opened": 2021,
            "park_name": "Pokey Park",
            "votes": 386,
        },
        {
            "ride_id": 44,
            "ride_name": "Motion Simulator",
            "ride_type": "Thrill Rides",
            "year_opened": 2016,
            "park_name": "Bumbly Beach",
            "votes": 285,
        },
        {
            "ride_id": 45,
            "ride_name": "3D Cinema",
            "ride_type": "Thrill Rides",
            "year_opened": 2019,
            "park_name": "Katie's Dreamland",
            "votes": 539,
        },
        {
            "ride_id": 46,
            "ride_name": "Top Spin",
            "ride_type": "Thrill Rides",
            "year_opened": 2006,
            "park_name": "Diamond Heights",
            "votes": 239,
        },
        {
            "ride_id": 47,
            "ride_name": "Dinghy Slide",
            "ride_type": "Water Rides",
            "year_opened": 2003,
            "park_name": "Leafy Lake",
            "votes": 583,
        },
        {
            "ride_id": 48,
            "ride_name": "Log Flume",
            "ride_type": "Water Rides",
            "year_opened": 2007,
            "park_name": "Diamond Heights",
            "votes": 739,
        },
        {
            "ride_id": 49,
            "ride_name": "River Rapids",
            "ride_type": "Water Rides",
            "year_opened": 2024,
            "park_name": "White Water Park",
            "votes": 920,
        },
        {
            "ride_id": 50,
            "ride_name": "Rowing Boats",
            "ride_type": "Water Rides",
            "year_opened": 2009,
            "park_name": "Evergreen Gardens",
            "votes": 392,
        },
        {
            "ride_id": 51,
            "ride_name": "Swans",
            "ride_type": "Water Rides",
            "year_opened": 2013,
            "park_name": "Bumbly Beach",
            "votes": 295,
        },
        {
            "ride_id": 52,
            "ride_name": "Canoes",
            "ride_type": "Water Rides",
            "year_opened": 2015,
            "park_name": "Trinity Islands",
            "votes": 21,
        },
        {
            "ride_id": 53,
            "ride_name": "Bumper Boats",
            "ride_type": "Water Rides",
            "year_opened": 2018,
            "park_name": "Katie's Dreamland",
            "votes": 520,
        },
        {
            "ride_id": 54,
            "ride_name": "Water Tricycles",
            "ride_type": "Water Rides",
            "year_opened": 2023,
            "park_name": "Pokey Park",
            "votes": 133,
        },
    ]
    assert result == expected


def test_modify_rides_data(db):
    result = modify_rides_data(db)
    expected = [
        {
            "ride_id": 1,
            "ride_name": "Steam Trains",
            "ride_type": "Transport Rides",
            "year_opened": 2005,
            "votes": 104,
            "park_id": 2,
        },
        {
            "ride_id": 2,
            "ride_name": "Small Monorail Cars",
            "ride_type": "Transport Rides",
            "year_opened": 2016,
            "votes": 749,
            "park_id": 7,
        },
        {
            "ride_id": 3,
            "ride_name": "Large Monorail Train",
            "ride_type": "Transport Rides",
            "year_opened": 2009,
            "votes": 194,
            "park_id": 5,
        },
        {
            "ride_id": 4,
            "ride_name": "Chairlift Cars",
            "ride_type": "Transport Rides",
            "year_opened": 2023,
            "votes": 438,
            "park_id": 10,
        },
        {
            "ride_id": 5,
            "ride_name": "Haunted House",
            "ride_type": "Gentle Rides",
            "year_opened": 2000,
            "votes": 84,
            "park_id": 2,
        },
        {
            "ride_id": 6,
            "ride_name": "Ferris Wheel",
            "ride_type": "Gentle Rides",
            "year_opened": 1999,
            "votes": 840,
            "park_id": 1,
        },
        {
            "ride_id": 7,
            "ride_name": "Hedge Maze",
            "ride_type": "Gentle Rides",
            "year_opened": 2009,
            "votes": 295,
            "park_id": 5,
        },
        {
            "ride_id": 8,
            "ride_name": "Merry-Go-Round",
            "ride_type": "Gentle Rides",
            "year_opened": 1999,
            "votes": 106,
            "park_id": 1,
        },
        {
            "ride_id": 9,
            "ride_name": "Observation Tower",
            "ride_type": "Gentle Rides",
            "year_opened": 2003,
            "votes": 720,
            "park_id": 3,
        },
        {
            "ride_id": 10,
            "ride_name": "Sportscars",
            "ride_type": "Gentle Rides",
            "year_opened": 2013,
            "votes": 1058,
            "park_id": 6,
        },
        {
            "ride_id": 11,
            "ride_name": "Racing Cars",
            "ride_type": "Gentle Rides",
            "year_opened": 2006,
            "votes": 20,
            "park_id": 4,
        },
        {
            "ride_id": 12,
            "ride_name": "Pickup Trucks",
            "ride_type": "Gentle Rides",
            "year_opened": 2015,
            "votes": 60,
            "park_id": 7,
        },
        {
            "ride_id": 13,
            "ride_name": "Cheshire Cats",
            "ride_type": "Gentle Rides",
            "year_opened": 2018,
            "votes": 306,
            "park_id": 8,
        },
        {
            "ride_id": 14,
            "ride_name": "Spiral Slide",
            "ride_type": "Gentle Rides",
            "year_opened": 2021,
            "votes": 481,
            "park_id": 9,
        },
        {
            "ride_id": 15,
            "ride_name": "Dodgems",
            "ride_type": "Gentle Rides",
            "year_opened": 2023,
            "votes": 82,
            "park_id": 10,
        },
        {
            "ride_id": 16,
            "ride_name": "Space Rings",
            "ride_type": "Gentle Rides",
            "year_opened": 2010,
            "votes": 1068,
            "park_id": 5,
        },
        {
            "ride_id": 17,
            "ride_name": "Wooden Roller Coaster",
            "ride_type": "Roller Coasters",
            "year_opened": 1999,
            "votes": 2059,
            "park_id": 1,
        },
        {
            "ride_id": 18,
            "ride_name": "Reversed Wooden Roller Coaster",
            "ride_type": "Roller Coasters",
            "year_opened": 2001,
            "votes": 1947,
            "park_id": 2,
        },
        {
            "ride_id": 19,
            "ride_name": "Wooden Wild Mouse",
            "ride_type": "Roller Coasters",
            "year_opened": 2000,
            "votes": 1396,
            "park_id": 1,
        },
        {
            "ride_id": 20,
            "ride_name": "Wooden Wild Mine Ride",
            "ride_type": "Roller Coasters",
            "year_opened": 2000,
            "votes": 1294,
            "park_id": 2,
        },
        {
            "ride_id": 21,
            "ride_name": "Ladybird Trains",
            "ride_type": "Roller Coasters",
            "year_opened": 2003,
            "votes": 857,
            "park_id": 3,
        },
        {
            "ride_id": 22,
            "ride_name": "Log Trains",
            "ride_type": "Roller Coasters",
            "year_opened": 2023,
            "votes": 920,
            "park_id": 10,
        },
        {
            "ride_id": 23,
            "ride_name": "Rocket Cars",
            "ride_type": "Roller Coasters",
            "year_opened": 2017,
            "votes": 1503,
            "park_id": 4,
        },
        {
            "ride_id": 24,
            "ride_name": "Spinning Cars",
            "ride_type": "Roller Coasters",
            "year_opened": 2003,
            "votes": 1058,
            "park_id": 3,
        },
        {
            "ride_id": 25,
            "ride_name": "Mine Train Coaster",
            "ride_type": "Roller Coasters",
            "year_opened": 2015,
            "votes": 1302,
            "park_id": 4,
        },
        {
            "ride_id": 26,
            "ride_name": "Looping Roller Coaster",
            "ride_type": "Roller Coasters",
            "year_opened": 2015,
            "votes": 1956,
            "park_id": 7,
        },
        {
            "ride_id": 27,
            "ride_name": "Backwards Roller Coaster Train",
            "ride_type": "Roller Coasters",
            "year_opened": 2024,
            "votes": 2057,
            "park_id": 10,
        },
        {
            "ride_id": 28,
            "ride_name": "Stand-up Roller Coaster",
            "ride_type": "Roller Coasters",
            "year_opened": 2015,
            "park_name": "Evergreen Garden",
            "votes": 503,
        },
        {
            "ride_id": 29,
            "ride_name": "Corkscrew Roller Coaster",
            "ride_type": "Roller Coasters",
            "year_opened": 2013,
            "votes": 1734,
            "park_id": 6,
        },
        {
            "ride_id": 30,
            "ride_name": "Suspended Swinging Cars",
            "ride_type": "Roller Coasters",
            "year_opened": 2013,
            "votes": 2056,
            "park_id": 4,
        },
        {
            "ride_id": 31,
            "ride_name": "Suspended Swinging Airplane Cars",
            "ride_type": "Roller Coasters",
            "year_opened": 2016,
            "votes": 2104,
            "park_id": 8,
        },
        {
            "ride_id": 32,
            "ride_name": "Mini Suspended Coaster",
            "ride_type": "Roller Coasters",
            "year_opened": 2015,
            "votes": 1845,
            "park_id": 7,
        },
        {
            "ride_id": 33,
            "ride_name": "Mini Suspended Flying Coaster",
            "ride_type": "Roller Coasters",
            "year_opened": 2020,
            "votes": 1003,
            "park_id": 7,
        },
        {
            "ride_id": 34,
            "ride_name": "Steeplechase",
            "ride_type": "Roller Coasters",
            "year_opened": 2017,
            "park_name": "Evergreen Garden",
            "votes": 927,
        },
        {
            "ride_id": 35,
            "ride_name": "Motorbike Races",
            "ride_type": "Roller Coasters",
            "year_opened": 2014,
            "votes": 1720,
            "park_id": 6,
        },
        {
            "ride_id": 36,
            "ride_name": "Bobsleigh Coaster",
            "ride_type": "Roller Coasters",
            "year_opened": 2021,
            "votes": 1940,
            "park_id": 9,
        },
        {
            "ride_id": 37,
            "ride_name": "Reverse Freefall Coaster",
            "ride_type": "Roller Coasters",
            "year_opened": 2022,
            "votes": 2312,
            "park_id": 7,
        },
        {
            "ride_id": 38,
            "ride_name": "Vertical Drop Roller Coaster",
            "ride_type": "Roller Coasters",
            "year_opened": 2021,
            "votes": 1840,
            "park_id": 9,
        },
        {
            "ride_id": 39,
            "ride_name": "Twist",
            "ride_type": "Thrill Rides",
            "year_opened": 2000,
            "votes": 48,
            "park_id": 2,
        },
        {
            "ride_id": 40,
            "ride_name": "Launched Freefall",
            "ride_type": "Thrill Rides",
            "year_opened": 2004,
            "votes": 375,
            "park_id": 3,
        },
        {
            "ride_id": 41,
            "ride_name": "Pirate Ship",
            "ride_type": "Thrill Rides",
            "year_opened": 1999,
            "votes": 857,
            "park_id": 1,
        },
        {
            "ride_id": 42,
            "ride_name": "Go Karts",
            "ride_type": "Thrill Rides",
            "year_opened": 2011,
            "votes": 127,
            "park_id": 5,
        },
        {
            "ride_id": 43,
            "ride_name": "Swinging Inverter Ship",
            "ride_type": "Thrill Rides",
            "year_opened": 2021,
            "votes": 386,
            "park_id": 9,
        },
        {
            "ride_id": 44,
            "ride_name": "Motion Simulator",
            "ride_type": "Thrill Rides",
            "year_opened": 2016,
            "votes": 285,
            "park_id": 6,
        },
        {
            "ride_id": 45,
            "ride_name": "3D Cinema",
            "ride_type": "Thrill Rides",
            "year_opened": 2019,
            "votes": 539,
            "park_id": 8,
        },
        {
            "ride_id": 46,
            "ride_name": "Top Spin",
            "ride_type": "Thrill Rides",
            "year_opened": 2006,
            "votes": 239,
            "park_id": 4,
        },
        {
            "ride_id": 47,
            "ride_name": "Dinghy Slide",
            "ride_type": "Water Rides",
            "year_opened": 2003,
            "votes": 583,
            "park_id": 3,
        },
        {
            "ride_id": 48,
            "ride_name": "Log Flume",
            "ride_type": "Water Rides",
            "year_opened": 2007,
            "votes": 739,
            "park_id": 4,
        },
        {
            "ride_id": 49,
            "ride_name": "River Rapids",
            "ride_type": "Water Rides",
            "year_opened": 2024,
            "votes": 920,
            "park_id": 10,
        },
        {
            "ride_id": 50,
            "ride_name": "Rowing Boats",
            "ride_type": "Water Rides",
            "year_opened": 2009,
            "votes": 392,
            "park_id": 5,
        },
        {
            "ride_id": 51,
            "ride_name": "Swans",
            "ride_type": "Water Rides",
            "year_opened": 2013,
            "votes": 295,
            "park_id": 6,
        },
        {
            "ride_id": 52,
            "ride_name": "Canoes",
            "ride_type": "Water Rides",
            "year_opened": 2015,
            "votes": 21,
            "park_id": 7,
        },
        {
            "ride_id": 53,
            "ride_name": "Bumper Boats",
            "ride_type": "Water Rides",
            "year_opened": 2018,
            "votes": 520,
            "park_id": 8,
        },
        {
            "ride_id": 54,
            "ride_name": "Water Tricycles",
            "ride_type": "Water Rides",
            "year_opened": 2023,
            "votes": 133,
            "park_id": 9,
        },
    ]
    assert result == expected

def test_get_raw_rides_data(rides):
    result = get_raw_rides_data(rides)
    expected = [
        {
            "ride_id": 1,
            "ride_name": "Steam Trains",
            "ride_type": "Transport Rides",
            "year_opened": 2005,
            "park_name": "Dynamite Dunes",
            "votes": 104,
        },
        {
            "ride_id": 2,
            "ride_name": "Small Monorail Cars",
            "ride_type": "Transport Rides",
            "year_opened": 2016,
            "park_name": "Trinity Islands",
            "votes": 749,
        },
        {
            "ride_id": 3,
            "ride_name": "Large Monorail Train",
            "ride_type": "Transport Rides",
            "year_opened": 2009,
            "park_name": "Evergreen Gardens",
            "votes": 194,
        },
        {
            "ride_id": 4,
            "ride_name": "Chairlift Cars",
            "ride_type": "Transport Rides",
            "year_opened": 2023,
            "park_name": "White Water Park",
            "votes": 438,
        },
        {
            "ride_id": 5,
            "ride_name": "Haunted House",
            "ride_type": "Gentle Rides",
            "year_opened": 2000,
            "park_name": "Dynamite Dunes",
            "votes": 84,
        },
        {
            "ride_id": 6,
            "ride_name": "Ferris Wheel",
            "ride_type": "Gentle Rides",
            "year_opened": 1999,
            "park_name": "Forest Frontiers",
            "votes": 840,
        },
        {
            "ride_id": 7,
            "ride_name": "Hedge Maze",
            "ride_type": "Gentle Rides",
            "year_opened": 2009,
            "park_name": "Evergreen Gardens",
            "votes": 295,
        },
        {
            "ride_id": 8,
            "ride_name": "Merry-Go-Round",
            "ride_type": "Gentle Rides",
            "year_opened": 1999,
            "park_name": "Forest Frontiers",
            "votes": 106,
        },
        {
            "ride_id": 9,
            "ride_name": "Observation Tower",
            "ride_type": "Gentle Rides",
            "year_opened": 2003,
            "park_name": "Leafy Lake",
            "votes": 720,
        },
        {
            "ride_id": 10,
            "ride_name": "Sportscars",
            "ride_type": "Gentle Rides",
            "year_opened": 2013,
            "park_name": "Bumbly Beach",
            "votes": 1058,
        },
        {
            "ride_id": 11,
            "ride_name": "Racing Cars",
            "ride_type": "Gentle Rides",
            "year_opened": 2006,
            "park_name": "Diamond Heights",
            "votes": 20,
        },
        {
            "ride_id": 12,
            "ride_name": "Pickup Trucks",
            "ride_type": "Gentle Rides",
            "year_opened": 2015,
            "park_name": "Trinity Islands",
            "votes": 60,
        },
        {
            "ride_id": 13,
            "ride_name": "Cheshire Cats",
            "ride_type": "Gentle Rides",
            "year_opened": 2018,
            "park_name": "Katie's Dreamland",
            "votes": 306,
        },
        {
            "ride_id": 14,
            "ride_name": "Spiral Slide",
            "ride_type": "Gentle Rides",
            "year_opened": 2021,
            "park_name": "Pokey Park",
            "votes": 481,
        },
        {
            "ride_id": 15,
            "ride_name": "Dodgems",
            "ride_type": "Gentle Rides",
            "year_opened": 2023,
            "park_name": "White Water Park",
            "votes": 82,
        },
        {
            "ride_id": 16,
            "ride_name": "Space Rings",
            "ride_type": "Gentle Rides",
            "year_opened": 2010,
            "park_name": "Evergreen Gardens",
            "votes": 1068,
        },
        {
            "ride_id": 17,
            "ride_name": "Wooden Roller Coaster",
            "ride_type": "Roller Coasters",
            "year_opened": 1999,
            "park_name": "Forest Frontiers",
            "votes": 2059,
        },
        {
            "ride_id": 18,
            "ride_name": "Reversed Wooden Roller Coaster",
            "ride_type": "Roller Coasters",
            "year_opened": 2001,
            "park_name": "Dynamite Dunes",
            "votes": 1947,
        },
        {
            "ride_id": 19,
            "ride_name": "Wooden Wild Mouse",
            "ride_type": "Roller Coasters",
            "year_opened": 2000,
            "park_name": "Forest Frontiers",
            "votes": 1396,
        },
        {
            "ride_id": 20,
            "ride_name": "Wooden Wild Mine Ride",
            "ride_type": "Roller Coasters",
            "year_opened": 2000,
            "park_name": "Dynamite Dunes",
            "votes": 1294,
        },
        {
            "ride_id": 21,
            "ride_name": "Ladybird Trains",
            "ride_type": "Roller Coasters",
            "year_opened": 2003,
            "park_name": "Leafy Lake",
            "votes": 857,
        },
        {
            "ride_id": 22,
            "ride_name": "Log Trains",
            "ride_type": "Roller Coasters",
            "year_opened": 2023,
            "park_name": "White Water Park",
            "votes": 920,
        },
        {
            "ride_id": 23,
            "ride_name": "Rocket Cars",
            "ride_type": "Roller Coasters",
            "year_opened": 2017,
            "park_name": "Diamond Heights",
            "votes": 1503,
        },
        {
            "ride_id": 24,
            "ride_name": "Spinning Cars",
            "ride_type": "Roller Coasters",
            "year_opened": 2003,
            "park_name": "Leafy Lake",
            "votes": 1058,
        },
        {
            "ride_id": 25,
            "ride_name": "Mine Train Coaster",
            "ride_type": "Roller Coasters",
            "year_opened": 2015,
            "park_name": "Diamond Heights",
            "votes": 1302,
        },
        {
            "ride_id": 26,
            "ride_name": "Looping Roller Coaster",
            "ride_type": "Roller Coasters",
            "year_opened": 2015,
            "park_name": "Trinity Islands",
            "votes": 1956,
        },
        {
            "ride_id": 27,
            "ride_name": "Backwards Roller Coaster Train",
            "ride_type": "Roller Coasters",
            "year_opened": 2024,
            "park_name": "White Water Park",
            "votes": 2057,
        },
        {
            "ride_id": 28,
            "ride_name": "Stand-up Roller Coaster",
            "ride_type": "Roller Coasters",
            "year_opened": 2015,
            "park_name": "Evergreen Garden",
            "votes": 503,
        },
        {
            "ride_id": 29,
            "ride_name": "Corkscrew Roller Coaster",
            "ride_type": "Roller Coasters",
            "year_opened": 2013,
            "park_name": "Bumbly Beach",
            "votes": 1734,
        },
        {
            "ride_id": 30,
            "ride_name": "Suspended Swinging Cars",
            "ride_type": "Roller Coasters",
            "year_opened": 2013,
            "park_name": "Diamond Heights",
            "votes": 2056,
        },
        {
            "ride_id": 31,
            "ride_name": "Suspended Swinging Airplane Cars",
            "ride_type": "Roller Coasters",
            "year_opened": 2016,
            "park_name": "Katie's Dreamland",
            "votes": 2104,
        },
        {
            "ride_id": 32,
            "ride_name": "Mini Suspended Coaster",
            "ride_type": "Roller Coasters",
            "year_opened": 2015,
            "park_name": "Trinity Islands",
            "votes": 1845,
        },
        {
            "ride_id": 33,
            "ride_name": "Mini Suspended Flying Coaster",
            "ride_type": "Roller Coasters",
            "year_opened": 2020,
            "park_name": "Trinity Islands",
            "votes": 1003,
        },
        {
            "ride_id": 34,
            "ride_name": "Steeplechase",
            "ride_type": "Roller Coasters",
            "year_opened": 2017,
            "park_name": "Evergreen Garden",
            "votes": 927,
        },
        {
            "ride_id": 35,
            "ride_name": "Motorbike Races",
            "ride_type": "Roller Coasters",
            "year_opened": 2014,
            "park_name": "Bumbly Beach",
            "votes": 1720,
        },
        {
            "ride_id": 36,
            "ride_name": "Bobsleigh Coaster",
            "ride_type": "Roller Coasters",
            "year_opened": 2021,
            "park_name": "Pokey Park",
            "votes": 1940,
        },
        {
            "ride_id": 37,
            "ride_name": "Reverse Freefall Coaster",
            "ride_type": "Roller Coasters",
            "year_opened": 2022,
            "park_name": "Trinity Islands",
            "votes": 2312,
        },
        {
            "ride_id": 38,
            "ride_name": "Vertical Drop Roller Coaster",
            "ride_type": "Roller Coasters",
            "year_opened": 2021,
            "park_name": "Pokey Park",
            "votes": 1840,
        },
        {
            "ride_id": 39,
            "ride_name": "Twist",
            "ride_type": "Thrill Rides",
            "year_opened": 2000,
            "park_name": "Dynamite Dunes",
            "votes": 48,
        },
        {
            "ride_id": 40,
            "ride_name": "Launched Freefall",
            "ride_type": "Thrill Rides",
            "year_opened": 2004,
            "park_name": "Leafy Lake",
            "votes": 375,
        },
        {
            "ride_id": 41,
            "ride_name": "Pirate Ship",
            "ride_type": "Thrill Rides",
            "year_opened": 1999,
            "park_name": "Forest Frontiers",
            "votes": 857,
        },
        {
            "ride_id": 42,
            "ride_name": "Go Karts",
            "ride_type": "Thrill Rides",
            "year_opened": 2011,
            "park_name": "Evergreen Gardens",
            "votes": 127,
        },
        {
            "ride_id": 43,
            "ride_name": "Swinging Inverter Ship",
            "ride_type": "Thrill Rides",
            "year_opened": 2021,
            "park_name": "Pokey Park",
            "votes": 386,
        },
        {
            "ride_id": 44,
            "ride_name": "Motion Simulator",
            "ride_type": "Thrill Rides",
            "year_opened": 2016,
            "park_name": "Bumbly Beach",
            "votes": 285,
        },
        {
            "ride_id": 45,
            "ride_name": "3D Cinema",
            "ride_type": "Thrill Rides",
            "year_opened": 2019,
            "park_name": "Katie's Dreamland",
            "votes": 539,
        },
        {
            "ride_id": 46,
            "ride_name": "Top Spin",
            "ride_type": "Thrill Rides",
            "year_opened": 2006,
            "park_name": "Diamond Heights",
            "votes": 239,
        },
        {
            "ride_id": 47,
            "ride_name": "Dinghy Slide",
            "ride_type": "Water Rides",
            "year_opened": 2003,
            "park_name": "Leafy Lake",
            "votes": 583,
        },
        {
            "ride_id": 48,
            "ride_name": "Log Flume",
            "ride_type": "Water Rides",
            "year_opened": 2007,
            "park_name": "Diamond Heights",
            "votes": 739,
        },
        {
            "ride_id": 49,
            "ride_name": "River Rapids",
            "ride_type": "Water Rides",
            "year_opened": 2024,
            "park_name": "White Water Park",
            "votes": 920,
        },
        {
            "ride_id": 50,
            "ride_name": "Rowing Boats",
            "ride_type": "Water Rides",
            "year_opened": 2009,
            "park_name": "Evergreen Gardens",
            "votes": 392,
        },
        {
            "ride_id": 51,
            "ride_name": "Swans",
            "ride_type": "Water Rides",
            "year_opened": 2013,
            "park_name": "Bumbly Beach",
            "votes": 295,
        },
        {
            "ride_id": 52,
            "ride_name": "Canoes",
            "ride_type": "Water Rides",
            "year_opened": 2015,
            "park_name": "Trinity Islands",
            "votes": 21,
        },
        {
            "ride_id": 53,
            "ride_name": "Bumper Boats",
            "ride_type": "Water Rides",
            "year_opened": 2018,
            "park_name": "Katie's Dreamland",
            "votes": 520,
        },
        {
            "ride_id": 54,
            "ride_name": "Water Tricycles",
            "ride_type": "Water Rides",
            "year_opened": 2023,
            "park_name": "Pokey Park",
            "votes": 133,
        },
    ]
    assert result == expected


def test_modify_raw_rides_data(rides, db):
    result = modify_raw_parks_data(rides, db)
    expected = [
        {
            "ride_id": 1,
            "ride_name": "Steam Trains",
            "ride_type": "Transport Rides",
            "year_opened": 2005,
            "votes": 104,
            "park_id": 2,
        },
        {
            "ride_id": 2,
            "ride_name": "Small Monorail Cars",
            "ride_type": "Transport Rides",
            "year_opened": 2016,
            "votes": 749,
            "park_id": 7,
        },
        {
            "ride_id": 3,
            "ride_name": "Large Monorail Train",
            "ride_type": "Transport Rides",
            "year_opened": 2009,
            "votes": 194,
            "park_id": 5,
        },
        {
            "ride_id": 4,
            "ride_name": "Chairlift Cars",
            "ride_type": "Transport Rides",
            "year_opened": 2023,
            "votes": 438,
            "park_id": 10,
        },
        {
            "ride_id": 5,
            "ride_name": "Haunted House",
            "ride_type": "Gentle Rides",
            "year_opened": 2000,
            "votes": 84,
            "park_id": 2,
        },
        {
            "ride_id": 6,
            "ride_name": "Ferris Wheel",
            "ride_type": "Gentle Rides",
            "year_opened": 1999,
            "votes": 840,
            "park_id": 1,
        },
        {
            "ride_id": 7,
            "ride_name": "Hedge Maze",
            "ride_type": "Gentle Rides",
            "year_opened": 2009,
            "votes": 295,
            "park_id": 5,
        },
        {
            "ride_id": 8,
            "ride_name": "Merry-Go-Round",
            "ride_type": "Gentle Rides",
            "year_opened": 1999,
            "votes": 106,
            "park_id": 1,
        },
        {
            "ride_id": 9,
            "ride_name": "Observation Tower",
            "ride_type": "Gentle Rides",
            "year_opened": 2003,
            "votes": 720,
            "park_id": 3,
        },
        {
            "ride_id": 10,
            "ride_name": "Sportscars",
            "ride_type": "Gentle Rides",
            "year_opened": 2013,
            "votes": 1058,
            "park_id": 6,
        },
        {
            "ride_id": 11,
            "ride_name": "Racing Cars",
            "ride_type": "Gentle Rides",
            "year_opened": 2006,
            "votes": 20,
            "park_id": 4,
        },
        {
            "ride_id": 12,
            "ride_name": "Pickup Trucks",
            "ride_type": "Gentle Rides",
            "year_opened": 2015,
            "votes": 60,
            "park_id": 7,
        },
        {
            "ride_id": 13,
            "ride_name": "Cheshire Cats",
            "ride_type": "Gentle Rides",
            "year_opened": 2018,
            "votes": 306,
            "park_id": 8,
        },
        {
            "ride_id": 14,
            "ride_name": "Spiral Slide",
            "ride_type": "Gentle Rides",
            "year_opened": 2021,
            "votes": 481,
            "park_id": 9,
        },
        {
            "ride_id": 15,
            "ride_name": "Dodgems",
            "ride_type": "Gentle Rides",
            "year_opened": 2023,
            "votes": 82,
            "park_id": 10,
        },
        {
            "ride_id": 16,
            "ride_name": "Space Rings",
            "ride_type": "Gentle Rides",
            "year_opened": 2010,
            "votes": 1068,
            "park_id": 5,
        },
        {
            "ride_id": 17,
            "ride_name": "Wooden Roller Coaster",
            "ride_type": "Roller Coasters",
            "year_opened": 1999,
            "votes": 2059,
            "park_id": 1,
        },
        {
            "ride_id": 18,
            "ride_name": "Reversed Wooden Roller Coaster",
            "ride_type": "Roller Coasters",
            "year_opened": 2001,
            "votes": 1947,
            "park_id": 2,
        },
        {
            "ride_id": 19,
            "ride_name": "Wooden Wild Mouse",
            "ride_type": "Roller Coasters",
            "year_opened": 2000,
            "votes": 1396,
            "park_id": 1,
        },
        {
            "ride_id": 20,
            "ride_name": "Wooden Wild Mine Ride",
            "ride_type": "Roller Coasters",
            "year_opened": 2000,
            "votes": 1294,
            "park_id": 2,
        },
        {
            "ride_id": 21,
            "ride_name": "Ladybird Trains",
            "ride_type": "Roller Coasters",
            "year_opened": 2003,
            "votes": 857,
            "park_id": 3,
        },
        {
            "ride_id": 22,
            "ride_name": "Log Trains",
            "ride_type": "Roller Coasters",
            "year_opened": 2023,
            "votes": 920,
            "park_id": 10,
        },
        {
            "ride_id": 23,
            "ride_name": "Rocket Cars",
            "ride_type": "Roller Coasters",
            "year_opened": 2017,
            "votes": 1503,
            "park_id": 4,
        },
        {
            "ride_id": 24,
            "ride_name": "Spinning Cars",
            "ride_type": "Roller Coasters",
            "year_opened": 2003,
            "votes": 1058,
            "park_id": 3,
        },
        {
            "ride_id": 25,
            "ride_name": "Mine Train Coaster",
            "ride_type": "Roller Coasters",
            "year_opened": 2015,
            "votes": 1302,
            "park_id": 4,
        },
        {
            "ride_id": 26,
            "ride_name": "Looping Roller Coaster",
            "ride_type": "Roller Coasters",
            "year_opened": 2015,
            "votes": 1956,
            "park_id": 7,
        },
        {
            "ride_id": 27,
            "ride_name": "Backwards Roller Coaster Train",
            "ride_type": "Roller Coasters",
            "year_opened": 2024,
            "votes": 2057,
            "park_id": 10,
        },
        {
            "ride_id": 28,
            "ride_name": "Stand-up Roller Coaster",
            "ride_type": "Roller Coasters",
            "year_opened": 2015,
            "park_name": "Evergreen Garden",
            "votes": 503,
        },
        {
            "ride_id": 29,
            "ride_name": "Corkscrew Roller Coaster",
            "ride_type": "Roller Coasters",
            "year_opened": 2013,
            "votes": 1734,
            "park_id": 6,
        },
        {
            "ride_id": 30,
            "ride_name": "Suspended Swinging Cars",
            "ride_type": "Roller Coasters",
            "year_opened": 2013,
            "votes": 2056,
            "park_id": 4,
        },
        {
            "ride_id": 31,
            "ride_name": "Suspended Swinging Airplane Cars",
            "ride_type": "Roller Coasters",
            "year_opened": 2016,
            "votes": 2104,
            "park_id": 8,
        },
        {
            "ride_id": 32,
            "ride_name": "Mini Suspended Coaster",
            "ride_type": "Roller Coasters",
            "year_opened": 2015,
            "votes": 1845,
            "park_id": 7,
        },
        {
            "ride_id": 33,
            "ride_name": "Mini Suspended Flying Coaster",
            "ride_type": "Roller Coasters",
            "year_opened": 2020,
            "votes": 1003,
            "park_id": 7,
        },
        {
            "ride_id": 34,
            "ride_name": "Steeplechase",
            "ride_type": "Roller Coasters",
            "year_opened": 2017,
            "park_name": "Evergreen Garden",
            "votes": 927,
        },
        {
            "ride_id": 35,
            "ride_name": "Motorbike Races",
            "ride_type": "Roller Coasters",
            "year_opened": 2014,
            "votes": 1720,
            "park_id": 6,
        },
        {
            "ride_id": 36,
            "ride_name": "Bobsleigh Coaster",
            "ride_type": "Roller Coasters",
            "year_opened": 2021,
            "votes": 1940,
            "park_id": 9,
        },
        {
            "ride_id": 37,
            "ride_name": "Reverse Freefall Coaster",
            "ride_type": "Roller Coasters",
            "year_opened": 2022,
            "votes": 2312,
            "park_id": 7,
        },
        {
            "ride_id": 38,
            "ride_name": "Vertical Drop Roller Coaster",
            "ride_type": "Roller Coasters",
            "year_opened": 2021,
            "votes": 1840,
            "park_id": 9,
        },
        {
            "ride_id": 39,
            "ride_name": "Twist",
            "ride_type": "Thrill Rides",
            "year_opened": 2000,
            "votes": 48,
            "park_id": 2,
        },
        {
            "ride_id": 40,
            "ride_name": "Launched Freefall",
            "ride_type": "Thrill Rides",
            "year_opened": 2004,
            "votes": 375,
            "park_id": 3,
        },
        {
            "ride_id": 41,
            "ride_name": "Pirate Ship",
            "ride_type": "Thrill Rides",
            "year_opened": 1999,
            "votes": 857,
            "park_id": 1,
        },
        {
            "ride_id": 42,
            "ride_name": "Go Karts",
            "ride_type": "Thrill Rides",
            "year_opened": 2011,
            "votes": 127,
            "park_id": 5,
        },
        {
            "ride_id": 43,
            "ride_name": "Swinging Inverter Ship",
            "ride_type": "Thrill Rides",
            "year_opened": 2021,
            "votes": 386,
            "park_id": 9,
        },
        {
            "ride_id": 44,
            "ride_name": "Motion Simulator",
            "ride_type": "Thrill Rides",
            "year_opened": 2016,
            "votes": 285,
            "park_id": 6,
        },
        {
            "ride_id": 45,
            "ride_name": "3D Cinema",
            "ride_type": "Thrill Rides",
            "year_opened": 2019,
            "votes": 539,
            "park_id": 8,
        },
        {
            "ride_id": 46,
            "ride_name": "Top Spin",
            "ride_type": "Thrill Rides",
            "year_opened": 2006,
            "votes": 239,
            "park_id": 4,
        },
        {
            "ride_id": 47,
            "ride_name": "Dinghy Slide",
            "ride_type": "Water Rides",
            "year_opened": 2003,
            "votes": 583,
            "park_id": 3,
        },
        {
            "ride_id": 48,
            "ride_name": "Log Flume",
            "ride_type": "Water Rides",
            "year_opened": 2007,
            "votes": 739,
            "park_id": 4,
        },
        {
            "ride_id": 49,
            "ride_name": "River Rapids",
            "ride_type": "Water Rides",
            "year_opened": 2024,
            "votes": 920,
            "park_id": 10,
        },
        {
            "ride_id": 50,
            "ride_name": "Rowing Boats",
            "ride_type": "Water Rides",
            "year_opened": 2009,
            "votes": 392,
            "park_id": 5,
        },
        {
            "ride_id": 51,
            "ride_name": "Swans",
            "ride_type": "Water Rides",
            "year_opened": 2013,
            "votes": 295,
            "park_id": 6,
        },
        {
            "ride_id": 52,
            "ride_name": "Canoes",
            "ride_type": "Water Rides",
            "year_opened": 2015,
            "votes": 21,
            "park_id": 7,
        },
        {
            "ride_id": 53,
            "ride_name": "Bumper Boats",
            "ride_type": "Water Rides",
            "year_opened": 2018,
            "votes": 520,
            "park_id": 8,
        },
        {
            "ride_id": 54,
            "ride_name": "Water Tricycles",
            "ride_type": "Water Rides",
            "year_opened": 2023,
            "votes": 133,
            "park_id": 9,
        },
    ]
    assert result == expected
